### ISSUE TITLE
Counter not working

### ISSUE THREAD

**Issue by KendallDoesCoding** [Valeron-T/personal-website#1]
Hey man,

The counter on the website is not working. I think the API used is not yet activated properly.

the following is shown permanently

"This page has been viewed **0** times"

**Comment by Valeron-T** [comment]
Hey,
Thanks for pointing this out! It was working fine for the first few days but not sure what happened.
Errors suggest API cannot access the db with user count.

**Comment by Valeron-T** [comment]
There was an error with functions config but its resolved now.
